# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\agirm\Desktop\Python_Master\Ders_4\Extra\video_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.kare_p1x = QtWidgets.QLineEdit(self.centralwidget)
        self.kare_p1x.setGeometry(QtCore.QRect(170, 120, 113, 20))
        self.kare_p1x.setInputMask("")
        self.kare_p1x.setText("")
        self.kare_p1x.setObjectName("kare_p1x")
        self.kare_p1y = QtWidgets.QLineEdit(self.centralwidget)
        self.kare_p1y.setGeometry(QtCore.QRect(170, 150, 113, 20))
        self.kare_p1y.setInputMask("");
        self.kare_p1y.setText("")
        self.kare_p1y.setObjectName("kare_p1y")
        self.kare_p2x = QtWidgets.QLineEdit(self.centralwidget)
        self.kare_p2x.setGeometry(QtCore.QRect(170, 180, 113, 20))
        self.kare_p2x.setInputMask("")
        self.kare_p2x.setText("")
        self.kare_p2x.setObjectName("kare_p2x")
        self.kare_p2y = QtWidgets.QLineEdit(self.centralwidget)
        self.kare_p2y.setGeometry(QtCore.QRect(170, 210, 113, 20))
        self.kare_p2y.setInputMask("")
        self.kare_p2y.setText("")
        self.kare_p2y.setObjectName("kare_p2y")
        self.kare_done = QtWidgets.QPushButton(self.centralwidget)
        self.kare_done.setGeometry(QtCore.QRect(170, 250, 111, 41))
        self.kare_done.setObjectName("kare_done")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(340, 60, 101, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.daire_py = QtWidgets.QLineEdit(self.centralwidget)
        self.daire_py.setGeometry(QtCore.QRect(330, 150, 113, 20))
        self.daire_py.setInputMask("")
        self.daire_py.setText("")
        self.daire_py.setObjectName("daire_py")
        self.daire_px = QtWidgets.QLineEdit(self.centralwidget)
        self.daire_px.setGeometry(QtCore.QRect(330, 120, 113, 20))
        self.daire_px.setInputMask("")
        self.daire_px.setText("")
        self.daire_px.setObjectName("daire_px")
        self.daire_done = QtWidgets.QPushButton(self.centralwidget)
        self.daire_done.setGeometry(QtCore.QRect(330, 250, 111, 41))
        self.daire_done.setObjectName("daire_done")
        self.daire_yaricap = QtWidgets.QLineEdit(self.centralwidget)
        self.daire_yaricap.setGeometry(QtCore.QRect(330, 180, 113, 20))
        self.daire_yaricap.setInputMask("")
        self.daire_yaricap.setText("")
        self.daire_yaricap.setObjectName("daire_yaricap")
        self.kare_p1x_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.kare_p1x_3.setGeometry(QtCore.QRect(490, 120, 113, 20))
        self.kare_p1x_3.setInputMask("")
        self.kare_p1x_3.setText("")
        self.kare_p1x_3.setObjectName("kare_p1x_3")
        self.yazi_done = QtWidgets.QPushButton(self.centralwidget)
        self.yazi_done.setGeometry(QtCore.QRect(490, 250, 111, 41))
        self.yazi_done.setObjectName("yazi_done")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.kare_p1x.setPlaceholderText(_translate("MainWindow", "Kare p1x"))
        self.kare_p1y.setPlaceholderText(_translate("MainWindow", "Kare p1y"))
        self.kare_p2x.setPlaceholderText(_translate("MainWindow", "Kare p2x"))
        self.kare_p2y.setPlaceholderText(_translate("MainWindow", "Kare p2y"))
        self.kare_done.setText(_translate("MainWindow", "Kare Bitir"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Kalabalık"))
        self.comboBox.setItemText(1, _translate("MainWindow", "New York"))
        self.daire_py.setPlaceholderText(_translate("MainWindow", "Daire Merkez py"))
        self.daire_px.setPlaceholderText(_translate("MainWindow", "Daire Merkez px"))
        self.daire_done.setText(_translate("MainWindow", "Daire Bitir"))
        self.daire_yaricap.setPlaceholderText(_translate("MainWindow", "Daire Yarıçap"))
        self.kare_p1x_3.setPlaceholderText(_translate("MainWindow", "Yazı Girin"))
        self.yazi_done.setText(_translate("MainWindow", "Yazı Bitir"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
